### ISSUE TITLE
Add More Michael Scott

### ISSUE THREAD

**Issue by MichaelWashburnJr** [corbanmailloux/thanks#3]
http://www.reddit.com/r/reactiongifs/comments/1xhujv/mrw_i_finally_find_a_short_informative_guide_on/

**Comment by corbanmailloux** [comment]
I'm looking back through my old repos and cleaning them up. I just discovered that [Gfycat was taken down in 2023](https://en.wikipedia.org/wiki/Gfycat#:~:text=On%20June%2030%2C%202023%2C%20Gfycat,the%20website%20was%20taken%20down.), so this is not worth updating.

But that is a good gif option, @MichaelWashburnJr. 🥇
